### ISSUE TITLE
Add Prerequisite: Dart Debug extension

### ISSUE THREAD

**Issue by geropl** [DanTup/gitpod-flutter-web#1]
We tried and ran into this: The instructions only work in Chrome with the [extension installed](https://chrome.google.com/webstore/detail/dart-debug-extension/eljbmlghnomdjgdjmbdekegdkbabckhm?hl=en).

**Comment by DanTup** [comment]
I'll update the readme. The extension should only be required for debugging though - if you "Start without debugging" I would expect it to work without (though of course, you won't be able to use debugging).
